version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    environment:
      - PORT=${PORT}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=${TYPEORM_HOST}
      - TYPEORM_URL=${TYPEORM_URL}
    ports:
      - ${PORT}:${PORT}
    command: npm run start
    restart: on-failure