version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    # env_file: .env
    environment:
      - PORT=${PORT}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=123456
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
    ports:
      - ${PORT}:${PORT}
    command: npm run start
    restart: on-failure
    image: shadezp/node